name: Check SQL Assignment 1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update and Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install mysql-server mysql-client -y

      - name: Start MySQL Service
        run: sudo /etc/init.d/mysql start

      - name: Create Initial Demo Database
        run: |
          echo "Creating demo database..."
          mysql -u$DB_USER -p$DB_PASSWORD -e "CREATE DATABASE demo;"

      - name: Validate SQL Queries
        run: |
          # Ensure answers.sql is present and not empty
          if [ ! -s ./answers.sql ]; then
            echo "The answers.sql file is missing or empty. Please provide your queries."
            exit 1
          fi

          echo "Executing queries from answers.sql..."
          output=$(mysql -u$DB_USER -p$DB_PASSWORD < ./answers.sql 2>&1)

          # Display the captured output
          echo "Execution Output:"
          echo "$output"

          # Check for SQL errors
          if echo "$output" | grep -q "ERROR"; then
            echo "SQL script execution failed due to errors."
            exit 1
          fi

      - name: Verify salesDB was created
        run: |
          if ! mysql -u$DB_USER -p$DB_PASSWORD -e "SHOW DATABASES LIKE 'salesDB';" | grep -q "salesDB"; then
            echo "Database salesDB was not created. Test failed."
            exit 1
          fi
          echo "Database salesDB exists."

      - name: Verify demo database was dropped
        run: |
          if mysql -u$DB_USER -p$DB_PASSWORD -e "SHOW DATABASES LIKE 'demo';" | grep -q "demo"; then
            echo "Database demo still exists. Test failed."
            exit 1
          fi
          echo "Database demo was successfully dropped."
